- type: loadout
  id: LoadoutLegionCenturionBaseArmor
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - CaesarLegionCenturion
  items:
    - N14ClothingOuterBaseCenturionArmor

- type: loadout
  id: LoadoutLegionCenturionHeavyArmor
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - CaesarLegionCenturion
  items:
    - N14ClothingOuterHeavyCenturionArmor

- type: loadout
  id: LoadoutLegionFrumentaryLightReconnaissanceArmor
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - CaesarLegionFrumentary
  items:
    - N14ClothingOuterLegionnaireLightReconnaissanceArmor

- type: loadout
  id: LoadoutLegionFrumentaryReconnaissanceArmor
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - CaesarLegionFrumentary
    - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionFrumentary
      min: 36000 # 10 hours veterancy unlock
  items:
    - N14ClothingOuterLegionnaireReconnaissanceArmor
