- type: department
  id: CaesarLegion
  description: department-CaesarLegion-description
  color: "#950202"
  roles:
  - CaesarLegionCenturion
  - CaesarLegionFrumentary
  - CaesarLegionDean
  - CaesarLegionLegionnaireVeteran
  - CaesarLegionLegionnaireWarrior
  - CaesarLegionLegionnaireRecruit
