- type: job
  id: CaesarLegionCenturion
  setPreference: true
  name: job-name-caesar-legion-centurion
  description: job-description-caesar-legion-centurion
  playTimeTracker: CaesarLegionCenturion
  requirements:
    - !type:DepartmentTimeRequirement
      department: CaesarLegion
      time: 0 # WL-only
    - !type:WhitelistRequirement
  startingGear: CaesarLegionCenturionGear
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: CaesarLegionCenturionGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    neck: ClothingNeckBlackScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsCenturion
    head: N14ClothingHeadHatCenturionHelmet
    gloves: N14ClothingHandsGlovesCenturion
    belt: N14Gladius
    pocket1: LegionCenturionloadoutkits
    pocket2: N14WeaponPipe10mm
    id: N14IDLegionaryMedalGold
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther

- type: playTimeTracker
  id: CaesarLegionCenturion
