- type: job
  id: CaesarLegionDean
  setPreference: true
  name: job-name-caesar-legion-dean
  description: job-description-caesar-legion-dean
  playTimeTracker: CaesarLegionDean
  requirements:
    - !type:DepartmentTimeRequirement
      department: CaesarLegion
      time: 36000 #10 hours
  startingGear: CaesarLegionDeanGear
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion-dean-supervisors
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: CaesarLegionDeanGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    neck: ClothingNeckRedScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatDeanHelmet
    gloves: N14ClothingHandsGlovesTribal
    outerClothing: N14ClothingOuterHeavyLegionnaireArmor
    belt: N14Gladius
    pocket1: LegionDeanloadoutkits
    pocket2: N14WeaponPipe10mm
    id: N14IDLegionaryMedalSilver3
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther

- type: playTimeTracker
  id: CaesarLegionDean
