- type: npcFaction
  id: CaesarLegion
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - WastelandAnimal
  - Zetan
